"""auto=vote

Revision ID: d788cb5c5892
Revises: c149c7fe0c6d
Create Date: 2023-07-18 17:46:24.214397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd788cb5c5892'
down_revision = 'c149c7fe0c6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
