"""auto-votes

Revision ID: fbb53aa3e588
Revises: c149c7fe0c6d
Create Date: 2023-07-18 17:47:20.729169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb53aa3e588'
down_revision = 'c149c7fe0c6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['post_id'], ['posts.id'],  ondelete="CASCADE"),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'],  ondelete="CASCADE"),
                    sa.PrimaryKeyConstraint('user_id', 'post_id'))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    pass
    # ### end Alembic commands ###
